name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master

    - name: setup-android
      uses: msfjarvis/setup-android@0.2
      with:
        run: chmod +x ./gradlew
        entrypoint: ./gradlew
        args: assemble
         
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: 0.1.20
        release_name: 0.1.20
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false
