name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.head_commit.message) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v1

    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assemble

    - name: Get Last Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set New Tag
      id: newtag
      shell: bash
      run: |
        chmod +x .github/tags.sh
        TAG=$(.github/tags.sh ${{steps.previoustag.outputs.tag }})
        echo "::set-output name=tag::$TAG"

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{steps.newtag.outputs.tag }}
        release_name:  ${{steps.newtag.outputs.tag }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false
