name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create Build
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        run: chmod +x ./gradlew
        script: assemble

    - name: Get Last Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set New Tag
      shell: bash
      run: |
        export TAG=$(chmod +x .github/tags.sh ${{steps.previoustag.outputs.tag }})
        echo $TAG

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $TAG
        release_name: $TAG
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false

