name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get Last Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set New Tag
      shell: bash
      run: |
        chmod +x .github/tags.sh
        export TAG=$(.github/tags.sh ${{steps.previoustag.outputs.tag }})
        echo $TAG

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_TEST: ${{ $(.github/tags.sh ${{steps.previoustag.outputs.tag }}) }}
      with:
        tag_name: $( TAG_TEST )
        release_name: $( TAG_TEST )
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false

