name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo tags $FIRST_NAME
        env:
          FIRST_NAME: curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/hadolint/hadolint/releases/latest
          middle_name: The
          Last_Name: Octocat
