name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Moving build to artifacts directory
        run: |
          chmod +x ./get_latest_release.sh
          echo tags ./get_latest_release.sh
