name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo curl --silent "https://api.github.com/repos/$1/releases/latest" | jq -r .tag_name
        env:
          FIRST_NAME: ${{ github.ref }}
          middle_name: The
          Last_Name: Octocat
