name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!