name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Moving build to artifacts directory
        run:
          echo tags $FIRST_NAME
        env:
          FIRST_NAME: sh ./tags.sh
          middle_name: The
          Last_Name: Octocat
